version: '3'

services:
  webapp:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - webapp

  git-server:
    container_name: git
    build:
      dockerfile: git.Dockerfile
      context: .
    command: >
      sh -c "git config --global user.name 'TanKianYun' &&
             git config --global user.email '2103012@sit.singaporetech.edu.sg'"
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./repo:/var/www/git

  jenkins:
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_conf:/opt/sonarqube/conf
    mem_limit: 3g

volumes:
  jenkins_home:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_conf:
